apiVersion: v1
kind: Service
metadata:
  name: moodmatch
  namespace: default
  labels:
    app: moodmatch
spec:
  type: LoadBalancer
  selector:
    app: moodmatch
  ports:
    - name: http
      port: 80
      targetPort: 8501
      protocol: TCP
